export const DOG_BREEDS = [
  "Akita",
  "American Bully",
  "Basset Hound",
  "Beagle",
  "Border Collie",
  "Boxer",
  "Buldogue Americano",
  "Bulldog Francês",
  "Bulldog Inglês",
  "Chow Chow",
  "Cocker Spaniel",
  "Dachshund (Salsicha)",
  "Dálmata",
  "Dobermann",
  "Golden Retriever",
  "Husky Siberiano",
  "Labrador Retriever",
  "Lhasa Apso",
  "Lulu da Pomerânia",
  "Maltês",
  "Pastor Alemão",
  "Pinscher",
  "Pitbull",
  "Poodle",
  "Rottweiler",
  "Schnauzer",
  "Shiba Inu",
  "Shih Tzu",
  "Spitz Alemão",
  "Viralata / SRD",
  "Weimaraner",
  "Yorkshire Terrier",
];

export const CAT_BREEDS = [
  "Abissínio",
  "Angorá",
  "Bengal",
  "Birmanês",
  "British Shorthair",
  "Chartreux",
  "Devon Rex",
  "Maine Coon",
  "Munchkin",
  "Norueguês da Floresta",
  "Persa",
  "Ragdoll",
  "Scottish Fold",
  "Siamês",
  "Siberiano",
  "Sphynx",
  "Viralata / SRD",
];
